### ISSUE TITLE
[Docs] Word cloud description needed

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report#110]
I add a word cloud render into report and it works fine on the [web site](http://www.x-lab.info/github-analysis-report/#/report).

![image](https://user-images.githubusercontent.com/8512426/94246196-03880800-ff4e-11ea-82f2-cebe901311e2.png)

But we still need to add more description about the word cloud like what is the data source and how to implement.

**Comment by sunshinemingo** [comment]
I can add some description later.
