### ISSUE TITLE
[Docs] Provide participants with a local environment for conducting tests.

### ISSUE THREAD

**Issue by QuakeWang** [X-lab2017/github-analysis-report#157]
While the developer can use `/sql-run` to detect the committed code, there is no way to preview the effect of the code until it is detected.Even if the submission is successful, there is still a barrier to participation for the vast majority of people.

**Comment by frank-zsy** [comment]
Yes, that is a problem. Actually, we use `analysis-report-bot` and `/sql-run` to expose our calculation ability to developers, but developers can not preview or test their code in local env.

The best way to solve this may be add a local tool to run sql and js code with some small test data, but we need to support clickhouse SQL syntax which is a big challenge.

Do you have any better ideas?

**Comment by frank-zsy** [comment]
Follow up in #162
