### ISSUE TITLE
[Discussion] CNCF operating picture

### ISSUE THREAD

**Issue by QuakeWang** [X-lab2017/github-analysis-report#174]
A diagram of how the relationship works describing the CNCF.

![CNCF](https://github.com/QuakeWang/quakewang.github.io/blob/master/imag/CNCF%E8%BF%90%E4%BD%9C%E5%9B%BE.png?raw=true)

**Comment by frank-zsy** [comment]
Thanks for the input. Did you draw this or there is an original one? And are you sure all CNCF projects will follow this procedure? Because I think this maybe the procedure of Kubernetes, I am not sure all projects in CNCF have WG.

**Comment by QuakeWang** [comment]
This picture was previously seen on a website about cloud native in China,and that is based on the official CNCF charter and project incubation conditions, which can be found in the CNCF project maturity model:https://www.cncf.io/projects/

**Comment by frank-zsy** [comment]
We will add CNCF procedure into report template in text form.
