### ISSUE TITLE
[Docs] Contributing guide doc needed.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report#22]
We need a comprehensive contributing guide for developers both in English and in Chinese.

The contributing guide can be like a traditional one but with the custom workflow of this project.

**Comment by frank-zsy** [comment]
@heming6666 Have you started. I assume that there are several parts we need to cover because different developers may interest in different part.

- Report, this is mostly about writing the report template, focus on the text part which is `REPORT_TEMPLATE.md`.
- SQL, this is about how to query data from database and render to report, mostly under `sqls/`.
- Docs, this is about collaborating on website, mostly under `docs/` folder.
- Governance, this is about how this project works, the workflow collaboration, mostly under `.github/` folder.

**Comment by heming6666** [comment]
> @heming6666 Have you started. I assume that there are several parts we need to cover because different developers may interest in different part.
> 
> * Report, this is mostly about writing the report template, focus on the text part which is `REPORT_TEMPLATE.md`.
> * SQL, this is about how to query data from database and render to report, mostly under `sqls/`.
> * Docs, this is about collaborating on website, mostly under `docs/` folder.
> * Governance, this is about how this project works, the workflow collaboration, mostly under `.github/` folder.

Got it! I will submit a WIP PR as soon as possible.
