### ISSUE TITLE
[Docs] We need to add more details to the report template

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report#25]
The report template is quite simple now, we can add more details into it, refer to [GitHub Analysis Report 2019](https://github.com/X-lab2017/github-analysis-report-2019/blob/master/REPORT.md) and may involve several SQL components development.

**Comment by xiaoya-Esther** [comment]
I would suggest enriching the report template from the following perspectives:

- The sum of active orgs
- Programming languages (which I found from the questionnaire a highly concerned topic)
- How frequently does each Event type occurs, especially the commonly used PushEvent, PullRequestEvent...
- "Top" statistics, the most active repos,  starred most repos, forked most repos…which are the angles to show how popular a repository is.

Besides, one thing that concerns me most is how to determine the “activeness” in the 2020 GitHub analysis report, would it be the same as the 2019 report, using the same active degree formula?

**Comment by frank-zsy** [comment]
@xiaoya-Esther Good suggestions! I think we can add new SQL components for active org, programming language, top star or fork and etc.

I don't really sure about event counts because for myself I am not sure what these number mean for me.

And for the activity calculation, now we still use the formula in 2019 report in the [component](https://github.com/X-lab2017/github-analysis-report-2020/tree/master/sqls/activity-repo-top), we can discuss on this to check whether we can have a better solution.

**Comment by xiaoya-Esther** [comment]
Different Event types could demonstrate the preferred coordination manner of developers, but yes, this could be reconsidered, it's not intuitive enough to explain a specific phenomenon

**Comment by frank-zsy** [comment]
Will split into some more specific issues to solve. Like programming language and top star.
