### ISSUE TITLE
[Feature] Case study repo id need to be added.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report#259]
As case study hypertrons component has been merged(#255 ) we need to add all repo id list to case study folders.

The format should be like ASF config (case-study/ASF/manifest.json).

- [x] ASF
- [x] CNCF
- [x] LF AI & Data
- [x] Wuhan2020

**Comment by sunshinemingo** [comment]
LF AI & Data Landscape contains 261 projects, only 5 graduated projects belong to LF AI & Data Foundation. Besides, there are 19 projects being incubated. So should I add all 261 repos or 24 repos ?

**Comment by frank-zsy** [comment]
> LF AI & Data Landscape contains 261 projects, only 5 graduated projects belong to LF AI & Data Foundation. Besides, there are 19 projects being incubated. So should I add all 261 repos or 24 repos ?

I think 24 repos with a landscape image is enough, WDYT?

**Comment by sunshinemingo** [comment]
> > LF AI & Data Landscape contains 261 projects, only 5 graduated projects belong to LF AI & Data Foundation. Besides, there are 19 projects being incubated. So should I add all 261 repos or 24 repos ?
> 
> I think 24 repos with a landscape image is enough, WDYT?

A landscape image is included in `REPORT_TEMPLATE.md`, and `manifest.json` contains 24 repos, right?

**Comment by frank-zsy** [comment]
Yes, landscape image will be an image link which can be the office image url in `TEMPLATE` file and repos in `manifest.json` like ASF does.

**Comment by sunshinemingo** [comment]
> Yes, landscape image will be an image link which can be the office image url in `TEMPLATE` file and repos in `manifest.json` like ASF does.
OK, I get it.
