### ISSUE TITLE
[Discussion]Definition of Chinese repo

### ISSUE THREAD

**Issue by zhuxiangning** [X-lab2017/github-analysis-report#368]
For example, **_apache/incubator-tvm_**. The initiator of this repo is a Chinese, but he is not in China, most of the developers are foreigners. Can such a project be defined as Chinese repo?

**Comment by frank-zsy** [comment]
Thanks, we will look into this.

**Comment by frank-zsy** [comment]
We will leave with it. The project still counts into Chinese projects but not in Apache China projects list.
