### ISSUE TITLE
[Discussion] I cannot delete the issue under this repository

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/github-analysis-report#512]
I cannot delete the issue, but I can only close the issue under this repository. I don’t know why the administrator set it up like this.
For some reasons, I posted two the same issues but couldn't delete them, yesterday.

**Comment by frank-zsy** [comment]
I understand what you mean but this is a basic setting of open source world which is what happened just happened. You can closed the redundant issue and that is enough since you opened two same issues accidentally.

**Comment by stevending1st** [comment]
> I understand what you mean but this is a basic setting of open source world which is what happened just happened. You can closed the redundant issue and that is enough since you opened two same issues accidentally.

Thanks for your explanation.
