### ISSUE TITLE
Data doesn't match the PDF

### ISSUE THREAD

**Issue by LawrenceHecht** [X-lab2017/github-analysis-report#513]
Several of the tables in the online report don't match those in the PDF. Look at the ones for the Chinese projects and companies.

**Comment by frank-zsy** [comment]
Thanks for your attention. Actually the data used in this repo and in the report is same but the algorithm we used in the report is slightly modified and not exactly same with the algorithm in this project.

We are now rewrite the architecture of this project and we will migrate the algorithms in the report into this project soon.

If you have any idea about the data or metrics, feel free to tell us by issues~

**Comment by LawrenceHecht** [comment]
And thank you for writing back. I just wanted confidence in the data. I am an active follower of the CHAOSS group's activities. I read your entire report.

**Comment by frank-zsy** [comment]
Thanks you for reading our report. I can guarantee the data is accurate because we can only use OLAP platform to process the massive data of GitHub event log. Although the algorithms will be improved as the project evolves so you may not get same result at different time point.

**Comment by LawrenceHecht** [comment]
Great. One more thing: here is a link: https://thenewstack.io/alibaba-github-repos-most-active-in-china/

**Comment by frank-zsy** [comment]
Great, thank you for your promotion of the report and project.

I will close this issue first now, if you have any other suggestion please feel free to fire another issue.
