### ISSUE TITLE
[Feature]Control email sendings by GitHub for people who watch this project

### ISSUE THREAD

**Issue by xiaoya-Esther** [X-lab2017/github-analysis-report#77]
People who "watch" this project may be overwhelmed by GitHub emails, for most conversations happen in the repository is about the analysis-report-bot updating the contributor .md file and merging PRs.

I think we should build a feasible solution to control the emails sent by bot, decrease redundant information so subscribed users can only focus on what's new in the project performed by "real people", and these new updates won't be rushed away by emails sent by bot.

**Comment by TieWay59** [comment]
There is a what option called releases only. 
~~If you play steam games~~ you will find it useful reading a new release notes.
Personally, I don't want to read every discussion. A regular notice will be nice for me.

**Comment by xiaoya-Esther** [comment]
Thanks! I was thinking of not-sending updates by the bot, but not sure whether this is technically feasible：）

**Comment by frank-zsy** [comment]
It is not feasible to filter the robot messages. The mechanism of `watch` is to receive notifies from GitHub of the repo changes. So GitHub will not judge the author to decide send the mail or not(actually it can but still don't have this feature and for now I can do nothing about this).
