### ISSUE TITLE
[Feature] Add statistics about working hour

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/github-analysis-report#83]
In [Apache Anual Report](https://www.apache.org/foundation/docs/FY2020AnnualReport.pdf), there are a lot of fun stuffs. Like a working hour slots graph to show activities in a day.

![image](https://user-images.githubusercontent.com/8512426/93047546-55e44180-f68f-11ea-8643-5613390932cb.png)

We can also add this to the report to show events distribution all over the world.

**Comment by will-ww** [comment]
Visualization can be a great help to show the ideas, and I am sure we can make the similar chart in the report. Anyone interested in this cool job ?

**Comment by frank-zsy** [comment]
I am sure we can use `svg` graph to implement this one to generate dynamic graph from different data source.

**Comment by will-ww** [comment]
Fantastic, let GOGOGOGOGO~
